# Generated by Django 4.2.8 on 2023-12-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Transcription', 'Transcription'), ('Caption', 'Caption')], max_length=50)),
                ('uploading_file', models.FileField(upload_to='uploads/')),
                ('storing_link', models.URLField()),
                ('plan', models.CharField(choices=[('Standard', 'Standard'), ('Speedy', 'Speedy'), ('Expedite', 'Expedite')], max_length=20)),
                ('text_format', models.CharField(blank=True, choices=[('Clean Verbatim', 'Clean Verbatim'), ('Full Verbatim', 'Full Verbatim')], max_length=20, null=True)),
                ('caption_method', models.CharField(blank=True, choices=[('Closed Caption', 'Closed Caption'), ('Burned in Caption', 'Burned in Caption')], max_length=20, null=True)),
            ],
        ),
    ]
